# Generated by Django 2.1.2 on 2018-10-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='starttime',
            field=models.CharField(choices=[(1, '8:00'), (2, '9:00'), (3, '10:00'), (4, '11:00'), (5, '12:00'), (6, '13:00')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default='1', max_length=2),
        ),
    ]
