# Generated by Django 2.1.2 on 2018-10-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20181012_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='sch_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.Grade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starttime',
            field=models.CharField(choices=[('1', '8:00'), ('2', '9:00'), ('3', '10:00'), ('4', '11:00'), ('5', '12:00'), ('6', '13:00')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default='1', max_length=2),
        ),
    ]
