# Generated by Django 2.1.2 on 2018-10-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20181012_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sch_grade',
        ),
    ]
